// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: kguard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Basename      string                 `protobuf:"bytes,2,opt,name=basename,proto3" json:"basename,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Pid           int64                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int64                  `protobuf:"varint,5,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Uid           int64                  `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           int64                  `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	Comm          string                 `protobuf:"bytes,8,opt,name=comm,proto3" json:"comm,omitempty"`
	Args          []string               `protobuf:"bytes,9,rep,name=args,proto3" json:"args,omitempty"`
	IsFileless    bool                   `protobuf:"varint,10,opt,name=is_fileless,json=isFileless,proto3" json:"is_fileless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessContext) Reset() {
	*x = ProcessContext{}
	mi := &file_kguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessContext) ProtoMessage() {}

func (x *ProcessContext) ProtoReflect() protoreflect.Message {
	mi := &file_kguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessContext.ProtoReflect.Descriptor instead.
func (*ProcessContext) Descriptor() ([]byte, []int) {
	return file_kguard_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProcessContext) GetBasename() string {
	if x != nil {
		return x.Basename
	}
	return ""
}

func (x *ProcessContext) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ProcessContext) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessContext) GetPpid() int64 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessContext) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessContext) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProcessContext) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProcessContext) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessContext) GetIsFileless() bool {
	if x != nil {
		return x.IsFileless
	}
	return false
}

type EventContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	AncestorSuspicious bool                   `protobuf:"varint,2,opt,name=ancestor_suspicious,json=ancestorSuspicious,proto3" json:"ancestor_suspicious,omitempty"`
	AncestorFilename   string                 `protobuf:"bytes,3,opt,name=ancestor_filename,json=ancestorFilename,proto3" json:"ancestor_filename,omitempty"`
	IsSuspiciousPath   bool                   `protobuf:"varint,4,opt,name=is_suspicious_path,json=isSuspiciousPath,proto3" json:"is_suspicious_path,omitempty"`
	MispredCount       uint64                 `protobuf:"varint,5,opt,name=mispred_count,json=mispredCount,proto3" json:"mispred_count,omitempty"`
	Process            *ProcessContext        `protobuf:"bytes,6,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventContext) Reset() {
	*x = EventContext{}
	mi := &file_kguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventContext) ProtoMessage() {}

func (x *EventContext) ProtoReflect() protoreflect.Message {
	mi := &file_kguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventContext.ProtoReflect.Descriptor instead.
func (*EventContext) Descriptor() ([]byte, []int) {
	return file_kguard_proto_rawDescGZIP(), []int{1}
}

func (x *EventContext) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventContext) GetAncestorSuspicious() bool {
	if x != nil {
		return x.AncestorSuspicious
	}
	return false
}

func (x *EventContext) GetAncestorFilename() string {
	if x != nil {
		return x.AncestorFilename
	}
	return ""
}

func (x *EventContext) GetIsSuspiciousPath() bool {
	if x != nil {
		return x.IsSuspiciousPath
	}
	return false
}

func (x *EventContext) GetMispredCount() uint64 {
	if x != nil {
		return x.MispredCount
	}
	return 0
}

func (x *EventContext) GetProcess() *ProcessContext {
	if x != nil {
		return x.Process
	}
	return nil
}

var File_kguard_proto protoreflect.FileDescriptor

const file_kguard_proto_rawDesc = "" +
	"\n" +
	"\fkguard.proto\x12\x06kguard\"\xeb\x01\n" +
	"\x0eProcessContext\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bbasename\x18\x02 \x01(\tR\bbasename\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x03R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x05 \x01(\x03R\x04ppid\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\x03R\x03uid\x12\x10\n" +
	"\x03gid\x18\a \x01(\x03R\x03gid\x12\x12\n" +
	"\x04comm\x18\b \x01(\tR\x04comm\x12\x12\n" +
	"\x04args\x18\t \x03(\tR\x04args\x12\x1f\n" +
	"\vis_fileless\x18\n" +
	" \x01(\bR\n" +
	"isFileless\"\x85\x02\n" +
	"\fEventContext\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12/\n" +
	"\x13ancestor_suspicious\x18\x02 \x01(\bR\x12ancestorSuspicious\x12+\n" +
	"\x11ancestor_filename\x18\x03 \x01(\tR\x10ancestorFilename\x12,\n" +
	"\x12is_suspicious_path\x18\x04 \x01(\bR\x10isSuspiciousPath\x12#\n" +
	"\rmispred_count\x18\x05 \x01(\x04R\fmispredCount\x120\n" +
	"\aprocess\x18\x06 \x01(\v2\x16.kguard.ProcessContextR\aprocessB\x15Z\x13k-guard/internal/pbb\x06proto3"

var (
	file_kguard_proto_rawDescOnce sync.Once
	file_kguard_proto_rawDescData []byte
)

func file_kguard_proto_rawDescGZIP() []byte {
	file_kguard_proto_rawDescOnce.Do(func() {
		file_kguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kguard_proto_rawDesc), len(file_kguard_proto_rawDesc)))
	})
	return file_kguard_proto_rawDescData
}

var file_kguard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kguard_proto_goTypes = []any{
	(*ProcessContext)(nil), // 0: kguard.ProcessContext
	(*EventContext)(nil),   // 1: kguard.EventContext
}
var file_kguard_proto_depIdxs = []int32{
	0, // 0: kguard.EventContext.process:type_name -> kguard.ProcessContext
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kguard_proto_init() }
func file_kguard_proto_init() {
	if File_kguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kguard_proto_rawDesc), len(file_kguard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kguard_proto_goTypes,
		DependencyIndexes: file_kguard_proto_depIdxs,
		MessageInfos:      file_kguard_proto_msgTypes,
	}.Build()
	File_kguard_proto = out.File
	file_kguard_proto_goTypes = nil
	file_kguard_proto_depIdxs = nil
}
