package audit

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"k-guard/internal/config"
)

// parsedRecord is used to unmarshal and validate the NDJSON generated by the logger
type parsedRecord struct {
	Timestamp string            `json:"timestamp"`
	Decision  string            `json:"decision"`
	EventType string            `json:"event_type"`
	RuleName  string            `json:"rule_name,omitempty"`
	Mitre     *config.MitreMeta `json:"mitre,omitempty"`
	PID       uint32            `json:"pid"`
	PPID      uint32            `json:"ppid"`
	UID       uint32            `json:"uid"`
	Comm      string            `json:"comm"`
	CgroupID  uint64            `json:"cgroup_id"`
	Target    string            `json:"target,omitempty"`
	Reason    string            `json:"reason"`
}

func TestLogger_BasicLoggingAndNDJSONFormat(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "subDir", "audit.log")

	logger, err := NewLogger(logPath)
	if err != nil {
		t.Fatalf("failed to create NewLogger: %v", err)
	}

	rec := Record{
		Decision:  DecisionBlock,
		EventType: "EXEC_BLOCKED",
		RuleName:  "block-nc",
		PID:       1234,
		PPID:      1000,
		UID:       0,
		Comm:      "nc",
		CgroupID:  5678,
		Target:    "/usr/bin/nc",
		Reason:    "LSM pre-exec hook blocked binary execution",
	}

	logger.Log(rec)

	if err := logger.Close(); err != nil {
		t.Fatalf("failed to close logger: %v", err)
	}

	// Read and verify file contents
	content, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("failed to read audit log: %v", err)
	}

	var parsed parsedRecord
	if err := json.Unmarshal(content, &parsed); err != nil {
		t.Fatalf("failed to parse output NDJSON string: %v\nRaw: %s", err, string(content))
	}

	if parsed.Decision != string(DecisionBlock) {
		t.Errorf("expected decision %q, got %q", DecisionBlock, parsed.Decision)
	}
	if parsed.EventType != "EXEC_BLOCKED" {
		t.Errorf("expected event_type 'EXEC_BLOCKED', got %q", parsed.EventType)
	}
	if parsed.RuleName != "block-nc" {
		t.Errorf("expected rule_name 'block-nc', got %q", parsed.RuleName)
	}
	if parsed.PID != 1234 || parsed.PPID != 1000 || parsed.UID != 0 || parsed.CgroupID != 5678 {
		t.Errorf("unexpected IDs in parsed output: %+v", parsed)
	}
	if parsed.Comm != "nc" || parsed.Target != "/usr/bin/nc" {
		t.Errorf("unexpected string fields in parsed output: %+v", parsed)
	}
	if parsed.Reason != "LSM pre-exec hook blocked binary execution" {
		t.Errorf("unexpected reason string: %q", parsed.Reason)
	}

	// Ensure timestamp is parsed properly
	if _, err := time.Parse(time.RFC3339Nano, parsed.Timestamp); err != nil {
		t.Errorf("timestamp is not valid RFC3339Nano string: %v", err)
	}
}

func TestLogger_MitreMetadataFormatting(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "audit_mitre.log")

	logger, err := NewLogger(logPath)
	if err != nil {
		t.Fatalf("failed to create NewLogger: %v", err)
	}

	rec := Record{
		Decision:  DecisionKill,
		EventType: "EXEC",
		RuleName:  "mitre-rule",
		Mitre: &config.MitreMeta{
			Tactic:      "Execution",
			TechniqueID: "T1059.004",
			Technique:   "Unix Shell",
		},
		PID:      2000,
		PPID:     1,
		UID:      1000,
		Comm:     "sh",
		CgroupID: 99,
		Reason:   "Process killed post-exec via rule action",
	}

	logger.Log(rec)
	_ = logger.Close()

	content, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("failed to read log file: %v", err)
	}

	var parsed parsedRecord
	if err := json.Unmarshal(content, &parsed); err != nil {
		t.Fatalf("failed to unmarshal JSON: %v", err)
	}

	if parsed.Mitre == nil {
		t.Fatalf("expected Mitre object to be non-nil")
	}
	if parsed.Mitre.Tactic != "Execution" {
		t.Errorf("expected tactic 'Execution', got %q", parsed.Mitre.Tactic)
	}
	if parsed.Mitre.TechniqueID != "T1059.004" {
		t.Errorf("expected technique_id 'T1059.004', got %q", parsed.Mitre.TechniqueID)
	}
	if parsed.Mitre.Technique != "Unix Shell" {
		t.Errorf("expected technique 'Unix Shell', got %q", parsed.Mitre.Technique)
	}
}

func TestLogger_NilSafety(t *testing.T) {
	var logger *Logger

	// Calling methods on nil pointer should not panic
	logger.Log(Record{Decision: DecisionBlock})

	if err := logger.Close(); err != nil {
		t.Errorf("expected nil error on nil Logger.Close(), got %v", err)
	}
}

func TestLogger_ConcurrentLogging(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "audit_concurrent.log")

	logger, err := NewLogger(logPath)
	if err != nil {
		t.Fatalf("failed to create logger: %v", err)
	}

	const goroutines = 10
	const logsPerRoutine = 50

	var wg sync.WaitGroup
	wg.Add(goroutines)

	for i := 0; i < goroutines; i++ {
		go func(id int) {
			defer wg.Done()
			for j := 0; j < logsPerRoutine; j++ {
				logger.Log(Record{
					Decision:  DecisionAlert,
					EventType: "TEST_CONCURRENT",
					PID:       uint32(id*100 + j),
					Comm:      "goroutine_proc",
					Reason:    "stress testing logger buffer",
				})
			}
		}(i)
	}

	wg.Wait()
	_ = logger.Close()

	file, err := os.Open(logPath)
	if err != nil {
		t.Fatalf("failed to open audit log: %v", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	lines := 0
	for scanner.Scan() {
		lines++
	}

	expectedLines := goroutines * logsPerRoutine
	if lines != expectedLines {
		t.Errorf("expected %d log lines, got %d", expectedLines, lines)
	}
}

func TestNewLogger_InvalidFileMode(t *testing.T) {
	tmpDir := t.TempDir()
	// Create a read-only directory to force file open error
	readOnlyDir := filepath.Join(tmpDir, "readonly")
	if err := os.Mkdir(readOnlyDir, 0400); err != nil {
		t.Fatalf("failed to create read-only dir: %v", err)
	}

	_, err := NewLogger(filepath.Join(readOnlyDir, "audit.log"))
	if err == nil {
		t.Error("expected error creating logger in read-only directory, got nil")
	}
}
