// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BPFConnectEvent struct {
	_        structs.HostLayout
	Hdr      BPFEventHdr
	Daddr    uint32
	Daddr6   [16]uint8
	Dport    uint16
	Family   uint16
	UnixPath [108]int8
	_        [4]byte
}

type BPFEventHdr struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	Pid                uint32
	Ppid               uint32
	Uid                uint32
	Gid                uint32
	CgroupId           uint64
	EventType          uint32
	Comm               [16]int8
	AncestorSuspicious uint8
	AncestorFilename   [256]int8
	_                  [3]byte
	ExeDev             uint64
	ExeIno             uint64
	Ret                int32
	_                  [4]byte
}

type BPFExecEvent struct {
	_             structs.HostLayout
	Hdr           BPFEventHdr
	Filename      [256]int8
	Args          [256]int8
	IsFileless    uint8
	PathTruncated uint8
	_             [6]byte
}

type BPFExecScratch struct {
	_    structs.HostLayout
	Args [256]int8
}

type BPFFileId struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

type BPFIouringEvent struct {
	_        structs.HostLayout
	Hdr      BPFEventHdr
	Opcode   uint8
	Filename [256]int8
	_        [7]byte
}

type BPFKmodEvent struct {
	_        structs.HostLayout
	Hdr      BPFEventHdr
	LoadType uint32
	_        [4]byte
}

type BPFLpeEvent struct {
	_      structs.HostLayout
	Hdr    BPFEventHdr
	OldUid uint32
	NewUid uint32
}

type BPFOpenEvent struct {
	_             structs.HostLayout
	Hdr           BPFEventHdr
	Filename      [256]int8
	IsFileless    uint8
	PathTruncated uint8
	_             [6]byte
}

type BPFProcessLineage struct {
	_                  structs.HostLayout
	ParentPid          uint32
	ExpectedUid        uint32
	SetuidAllowed      uint8
	SuspiciousAncestor uint8
	Pad                [2]uint8
	AncestorFilename   [256]int8
}

type BPFPtraceEvent struct {
	_          structs.HostLayout
	Hdr        BPFEventHdr
	TargetPid  uint32
	Mode       uint32
	CallerComm [64]int8
	TargetComm [64]int8
}

type BPFScratchBuffer struct {
	_       structs.HostLayout
	Primary [256]int8
	Walk    [256]int8
	Lin     BPFProcessLineage
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	BPFMapAllowedPtraceAttaches    = "allowed_ptrace_attaches"
	BPFMapBlockedPaths             = "blocked_paths"
	BPFMapBlockedWritePaths        = "blocked_write_paths"
	BPFMapContainerCgroups         = "container_cgroups"
	BPFMapExecScratchMap           = "exec_scratch_map"
	BPFMapLineageMap               = "lineage_map"
	BPFMapRb                       = "rb"
	BPFMapScratchMap               = "scratch_map"
	BPFMapSensitiveWritePaths      = "sensitive_write_paths"
	BPFMapSuspiciousPaths          = "suspicious_paths"
	BPFProgKguardKernelLoadData    = "kguard_kernel_load_data"
	BPFProgKguardKernelReadFile    = "kguard_kernel_read_file"
	BPFProgKguardTaskFixSetuid     = "kguard_task_fix_setuid"
	BPFProgLsmBpfCmd               = "lsm_bpf_cmd"
	BPFProgLsmBprmCheck            = "lsm_bprm_check"
	BPFProgLsmFileOpen             = "lsm_file_open"
	BPFProgLsmPtraceAccessCheck    = "lsm_ptrace_access_check"
	BPFProgLsmTaskKill             = "lsm_task_kill"
	BPFProgTpConnect               = "tp_connect"
	BPFProgTpExecve                = "tp_execve"
	BPFProgTpInitModule            = "tp_init_module"
	BPFProgTpIoUringSubmitReq      = "tp_io_uring_submit_req"
	BPFProgTpMemfdCreate           = "tp_memfd_create"
	BPFProgTpOpenat                = "tp_openat"
	BPFProgTpOpenat2               = "tp_openat2"
	BPFProgTpPtrace                = "tp_ptrace"
	BPFProgTpSchedexec             = "tp_schedexec"
	BPFProgTpSchedfork             = "tp_schedfork"
	BPFProgTpSetuid                = "tp_setuid"
	BPFVarEnforcementEnabled       = "enforcement_enabled"
	BPFVarKmodEnforcementEnabled   = "kmod_enforcement_enabled"
	BPFVarPtraceEnforcementEnabled = "ptrace_enforcement_enabled"
	BPFVarSelfPid                  = "self_pid"
	BPFVarUnusedConnectEvent       = "unused_connect_event"
	BPFVarUnusedEventHdr           = "unused_event_hdr"
	BPFVarUnusedExecEvent          = "unused_exec_event"
	BPFVarUnusedIouringEvent       = "unused_iouring_event"
	BPFVarUnusedKmodEvent          = "unused_kmod_event"
	BPFVarUnusedLpeEvent           = "unused_lpe_event"
	BPFVarUnusedOpenEvent          = "unused_open_event"
	BPFVarUnusedPtraceEvent        = "unused_ptrace_event"
)

// LoadBPF returns the embedded CollectionSpec for BPF.
func LoadBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BPF: %w", err)
	}

	return spec, err
}

// LoadBPFObjects loads BPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BPFObjects
//	*BPFPrograms
//	*BPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBPFObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFSpecs struct {
	BPFProgramSpecs
	BPFMapSpecs
	BPFVariableSpecs
}

// BPFProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFProgramSpecs struct {
	KguardKernelLoadData *ebpf.ProgramSpec `ebpf:"kguard_kernel_load_data"`
	KguardKernelReadFile *ebpf.ProgramSpec `ebpf:"kguard_kernel_read_file"`
	KguardTaskFixSetuid  *ebpf.ProgramSpec `ebpf:"kguard_task_fix_setuid"`
	LsmBpfCmd            *ebpf.ProgramSpec `ebpf:"lsm_bpf_cmd"`
	LsmBprmCheck         *ebpf.ProgramSpec `ebpf:"lsm_bprm_check"`
	LsmFileOpen          *ebpf.ProgramSpec `ebpf:"lsm_file_open"`
	LsmPtraceAccessCheck *ebpf.ProgramSpec `ebpf:"lsm_ptrace_access_check"`
	LsmTaskKill          *ebpf.ProgramSpec `ebpf:"lsm_task_kill"`
	TpConnect            *ebpf.ProgramSpec `ebpf:"tp_connect"`
	TpExecve             *ebpf.ProgramSpec `ebpf:"tp_execve"`
	TpInitModule         *ebpf.ProgramSpec `ebpf:"tp_init_module"`
	TpIoUringSubmitReq   *ebpf.ProgramSpec `ebpf:"tp_io_uring_submit_req"`
	TpMemfdCreate        *ebpf.ProgramSpec `ebpf:"tp_memfd_create"`
	TpOpenat             *ebpf.ProgramSpec `ebpf:"tp_openat"`
	TpOpenat2            *ebpf.ProgramSpec `ebpf:"tp_openat2"`
	TpPtrace             *ebpf.ProgramSpec `ebpf:"tp_ptrace"`
	TpSchedexec          *ebpf.ProgramSpec `ebpf:"tp_schedexec"`
	TpSchedfork          *ebpf.ProgramSpec `ebpf:"tp_schedfork"`
	TpSetuid             *ebpf.ProgramSpec `ebpf:"tp_setuid"`
}

// BPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFMapSpecs struct {
	AllowedPtraceAttaches *ebpf.MapSpec `ebpf:"allowed_ptrace_attaches"`
	BlockedPaths          *ebpf.MapSpec `ebpf:"blocked_paths"`
	BlockedWritePaths     *ebpf.MapSpec `ebpf:"blocked_write_paths"`
	ContainerCgroups      *ebpf.MapSpec `ebpf:"container_cgroups"`
	ExecScratchMap        *ebpf.MapSpec `ebpf:"exec_scratch_map"`
	LineageMap            *ebpf.MapSpec `ebpf:"lineage_map"`
	Rb                    *ebpf.MapSpec `ebpf:"rb"`
	ScratchMap            *ebpf.MapSpec `ebpf:"scratch_map"`
	SensitiveWritePaths   *ebpf.MapSpec `ebpf:"sensitive_write_paths"`
	SuspiciousPaths       *ebpf.MapSpec `ebpf:"suspicious_paths"`
}

// BPFVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFVariableSpecs struct {
	EnforcementEnabled       *ebpf.VariableSpec `ebpf:"enforcement_enabled"`
	KmodEnforcementEnabled   *ebpf.VariableSpec `ebpf:"kmod_enforcement_enabled"`
	PtraceEnforcementEnabled *ebpf.VariableSpec `ebpf:"ptrace_enforcement_enabled"`
	SelfPid                  *ebpf.VariableSpec `ebpf:"self_pid"`
	UnusedConnectEvent       *ebpf.VariableSpec `ebpf:"unused_connect_event"`
	UnusedEventHdr           *ebpf.VariableSpec `ebpf:"unused_event_hdr"`
	UnusedExecEvent          *ebpf.VariableSpec `ebpf:"unused_exec_event"`
	UnusedIouringEvent       *ebpf.VariableSpec `ebpf:"unused_iouring_event"`
	UnusedKmodEvent          *ebpf.VariableSpec `ebpf:"unused_kmod_event"`
	UnusedLpeEvent           *ebpf.VariableSpec `ebpf:"unused_lpe_event"`
	UnusedOpenEvent          *ebpf.VariableSpec `ebpf:"unused_open_event"`
	UnusedPtraceEvent        *ebpf.VariableSpec `ebpf:"unused_ptrace_event"`
}

// BPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFObjects struct {
	BPFPrograms
	BPFMaps
	BPFVariables
}

func (o *BPFObjects) Close() error {
	return _BPFClose(
		&o.BPFPrograms,
		&o.BPFMaps,
	)
}

// BPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFMaps struct {
	AllowedPtraceAttaches *ebpf.Map `ebpf:"allowed_ptrace_attaches"`
	BlockedPaths          *ebpf.Map `ebpf:"blocked_paths"`
	BlockedWritePaths     *ebpf.Map `ebpf:"blocked_write_paths"`
	ContainerCgroups      *ebpf.Map `ebpf:"container_cgroups"`
	ExecScratchMap        *ebpf.Map `ebpf:"exec_scratch_map"`
	LineageMap            *ebpf.Map `ebpf:"lineage_map"`
	Rb                    *ebpf.Map `ebpf:"rb"`
	ScratchMap            *ebpf.Map `ebpf:"scratch_map"`
	SensitiveWritePaths   *ebpf.Map `ebpf:"sensitive_write_paths"`
	SuspiciousPaths       *ebpf.Map `ebpf:"suspicious_paths"`
}

func (m *BPFMaps) Close() error {
	return _BPFClose(
		m.AllowedPtraceAttaches,
		m.BlockedPaths,
		m.BlockedWritePaths,
		m.ContainerCgroups,
		m.ExecScratchMap,
		m.LineageMap,
		m.Rb,
		m.ScratchMap,
		m.SensitiveWritePaths,
		m.SuspiciousPaths,
	)
}

// BPFVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFVariables struct {
	EnforcementEnabled       *ebpf.Variable `ebpf:"enforcement_enabled"`
	KmodEnforcementEnabled   *ebpf.Variable `ebpf:"kmod_enforcement_enabled"`
	PtraceEnforcementEnabled *ebpf.Variable `ebpf:"ptrace_enforcement_enabled"`
	SelfPid                  *ebpf.Variable `ebpf:"self_pid"`
	UnusedConnectEvent       *ebpf.Variable `ebpf:"unused_connect_event"`
	UnusedEventHdr           *ebpf.Variable `ebpf:"unused_event_hdr"`
	UnusedExecEvent          *ebpf.Variable `ebpf:"unused_exec_event"`
	UnusedIouringEvent       *ebpf.Variable `ebpf:"unused_iouring_event"`
	UnusedKmodEvent          *ebpf.Variable `ebpf:"unused_kmod_event"`
	UnusedLpeEvent           *ebpf.Variable `ebpf:"unused_lpe_event"`
	UnusedOpenEvent          *ebpf.Variable `ebpf:"unused_open_event"`
	UnusedPtraceEvent        *ebpf.Variable `ebpf:"unused_ptrace_event"`
}

// BPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFPrograms struct {
	KguardKernelLoadData *ebpf.Program `ebpf:"kguard_kernel_load_data"`
	KguardKernelReadFile *ebpf.Program `ebpf:"kguard_kernel_read_file"`
	KguardTaskFixSetuid  *ebpf.Program `ebpf:"kguard_task_fix_setuid"`
	LsmBpfCmd            *ebpf.Program `ebpf:"lsm_bpf_cmd"`
	LsmBprmCheck         *ebpf.Program `ebpf:"lsm_bprm_check"`
	LsmFileOpen          *ebpf.Program `ebpf:"lsm_file_open"`
	LsmPtraceAccessCheck *ebpf.Program `ebpf:"lsm_ptrace_access_check"`
	LsmTaskKill          *ebpf.Program `ebpf:"lsm_task_kill"`
	TpConnect            *ebpf.Program `ebpf:"tp_connect"`
	TpExecve             *ebpf.Program `ebpf:"tp_execve"`
	TpInitModule         *ebpf.Program `ebpf:"tp_init_module"`
	TpIoUringSubmitReq   *ebpf.Program `ebpf:"tp_io_uring_submit_req"`
	TpMemfdCreate        *ebpf.Program `ebpf:"tp_memfd_create"`
	TpOpenat             *ebpf.Program `ebpf:"tp_openat"`
	TpOpenat2            *ebpf.Program `ebpf:"tp_openat2"`
	TpPtrace             *ebpf.Program `ebpf:"tp_ptrace"`
	TpSchedexec          *ebpf.Program `ebpf:"tp_schedexec"`
	TpSchedfork          *ebpf.Program `ebpf:"tp_schedfork"`
	TpSetuid             *ebpf.Program `ebpf:"tp_setuid"`
}

func (p *BPFPrograms) Close() error {
	return _BPFClose(
		p.KguardKernelLoadData,
		p.KguardKernelReadFile,
		p.KguardTaskFixSetuid,
		p.LsmBpfCmd,
		p.LsmBprmCheck,
		p.LsmFileOpen,
		p.LsmPtraceAccessCheck,
		p.LsmTaskKill,
		p.TpConnect,
		p.TpExecve,
		p.TpInitModule,
		p.TpIoUringSubmitReq,
		p.TpMemfdCreate,
		p.TpOpenat,
		p.TpOpenat2,
		p.TpPtrace,
		p.TpSchedexec,
		p.TpSchedfork,
		p.TpSetuid,
	)
}

func _BPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BPFBytes []byte
