// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type BPFExecScratch struct{ Argv0 [64]int8 }

type BPFKguardEvent struct {
	TimestampNs        uint64
	Pid                uint32
	Ppid               uint32
	Uid                uint32
	Gid                uint32
	CgroupId           uint64
	EventType          uint32
	Ret                int32
	Comm               [16]int8
	Filename           [256]int8
	Argv0              [64]int8
	Daddr              uint32
	Daddr6             [16]uint8
	Dport              uint16
	Family             uint16
	UnixPath           [108]int8
	WriteFd            uint32
	WriteCount         uint64
	WriteBuf           [64]int8
	AncestorSuspicious uint8
	AncestorFilename   [256]int8
	PathTruncated      uint8
	_                  [6]byte
}

type BPFPathScratch struct {
	Primary [256]int8
	Walk    [256]int8
}

type BPFProcessLineage struct {
	ParentPid          uint32
	SuspiciousAncestor uint8
	AncestorFilename   [256]int8
	_                  [3]byte
}

// LoadBPF returns the embedded CollectionSpec for BPF.
func LoadBPF() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BPFBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BPF: %w", err)
	}

	return spec, err
}

// LoadBPFObjects loads BPF and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BPFObjects
//	*BPFPrograms
//	*BPFMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBPFObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBPF()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BPFSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFSpecs struct {
	BPFProgramSpecs
	BPFMapSpecs
}

// BPFSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFProgramSpecs struct {
	LsmBprmCheck  *ebpf.ProgramSpec `ebpf:"lsm_bprm_check"`
	TpConnect     *ebpf.ProgramSpec `ebpf:"tp_connect"`
	TpExecve      *ebpf.ProgramSpec `ebpf:"tp_execve"`
	TpInitModule  *ebpf.ProgramSpec `ebpf:"tp_init_module"`
	TpMemfdCreate *ebpf.ProgramSpec `ebpf:"tp_memfd_create"`
	TpOpenat      *ebpf.ProgramSpec `ebpf:"tp_openat"`
	TpOpenat2     *ebpf.ProgramSpec `ebpf:"tp_openat2"`
	TpPtrace      *ebpf.ProgramSpec `ebpf:"tp_ptrace"`
	TpSchedexec   *ebpf.ProgramSpec `ebpf:"tp_schedexec"`
	TpSchedfork   *ebpf.ProgramSpec `ebpf:"tp_schedfork"`
	TpSetuid      *ebpf.ProgramSpec `ebpf:"tp_setuid"`
}

// BPFMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BPFMapSpecs struct {
	BlockedPaths        *ebpf.MapSpec `ebpf:"blocked_paths"`
	EnforcementEnabled  *ebpf.MapSpec `ebpf:"enforcement_enabled"`
	ExecScratchMap      *ebpf.MapSpec `ebpf:"exec_scratch_map"`
	LineageMap          *ebpf.MapSpec `ebpf:"lineage_map"`
	PathScratchMap      *ebpf.MapSpec `ebpf:"path_scratch_map"`
	Rb                  *ebpf.MapSpec `ebpf:"rb"`
	SensitiveWritePaths *ebpf.MapSpec `ebpf:"sensitive_write_paths"`
	SuspiciousPaths     *ebpf.MapSpec `ebpf:"suspicious_paths"`
}

// BPFObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFObjects struct {
	BPFPrograms
	BPFMaps
}

func (o *BPFObjects) Close() error {
	return _BPFClose(
		&o.BPFPrograms,
		&o.BPFMaps,
	)
}

// BPFMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFMaps struct {
	BlockedPaths        *ebpf.Map `ebpf:"blocked_paths"`
	EnforcementEnabled  *ebpf.Map `ebpf:"enforcement_enabled"`
	ExecScratchMap      *ebpf.Map `ebpf:"exec_scratch_map"`
	LineageMap          *ebpf.Map `ebpf:"lineage_map"`
	PathScratchMap      *ebpf.Map `ebpf:"path_scratch_map"`
	Rb                  *ebpf.Map `ebpf:"rb"`
	SensitiveWritePaths *ebpf.Map `ebpf:"sensitive_write_paths"`
	SuspiciousPaths     *ebpf.Map `ebpf:"suspicious_paths"`
}

func (m *BPFMaps) Close() error {
	return _BPFClose(
		m.BlockedPaths,
		m.EnforcementEnabled,
		m.ExecScratchMap,
		m.LineageMap,
		m.PathScratchMap,
		m.Rb,
		m.SensitiveWritePaths,
		m.SuspiciousPaths,
	)
}

// BPFPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBPFObjects or ebpf.CollectionSpec.LoadAndAssign.
type BPFPrograms struct {
	LsmBprmCheck  *ebpf.Program `ebpf:"lsm_bprm_check"`
	TpConnect     *ebpf.Program `ebpf:"tp_connect"`
	TpExecve      *ebpf.Program `ebpf:"tp_execve"`
	TpInitModule  *ebpf.Program `ebpf:"tp_init_module"`
	TpMemfdCreate *ebpf.Program `ebpf:"tp_memfd_create"`
	TpOpenat      *ebpf.Program `ebpf:"tp_openat"`
	TpOpenat2     *ebpf.Program `ebpf:"tp_openat2"`
	TpPtrace      *ebpf.Program `ebpf:"tp_ptrace"`
	TpSchedexec   *ebpf.Program `ebpf:"tp_schedexec"`
	TpSchedfork   *ebpf.Program `ebpf:"tp_schedfork"`
	TpSetuid      *ebpf.Program `ebpf:"tp_setuid"`
}

func (p *BPFPrograms) Close() error {
	return _BPFClose(
		p.LsmBprmCheck,
		p.TpConnect,
		p.TpExecve,
		p.TpInitModule,
		p.TpMemfdCreate,
		p.TpOpenat,
		p.TpOpenat2,
		p.TpPtrace,
		p.TpSchedexec,
		p.TpSchedfork,
		p.TpSetuid,
	)
}

func _BPFClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BPFBytes []byte
